### ISSUE TITLE
Feature Request: Generate META6 with CLI

### ISSUE THREAD

**Issue by littlebenlittle** [jonathanstowe/META6#28]
A user friendly CLI will make it easier to publish Raku modules.

## Major Targets

- [ ] Generate `provides` by specifying one or more target directory (default `lib/`)
- [ ] Generate `depends` using the contents of the directories referenced by `provides`
- [ ] Support for interactive configuration, static configuration, and flag arguments

**Comment by jonathanstowe** [comment]
Hi,
Thanks for the suggestions.

I've always intended that his module should allow for _other software_ providing that functionality without actually providing these things itself:  I still consider the primary purpose of this module to describe the META format for `Test::META` but made it separately because it might be useful to people who didn't want the testing functionality, similarly I'm not keen on adding additional functionality that goes further than _description_ because it may not be useful to people who only use it as a dependency of `Test::Meta` or already do something else with it.

In the first instance I'd suggest checking out [META6::bin](https://github.com/gfldex/raku-meta6-bin) which uses this module and may already do most of what you want.
